apps/book_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'books'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<id>\d+)/add_book$', views.add_book, name='add_book'),
    url(r'^(?P<id>\d+)/$', views.create_data, name='create_data'),
    url(r'^(?P<id>\d+)/(?P<book_id>\d+)/book_review$', views.show_book, name='show_book'),
    url(r'^(?P<id>\d+)/(?P<book_id>\d+)/add_review$', views.add_book_review, name='add_book_review'),
]

apps/user_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sign_up$', views.signUp_test, name='sign_up'),
    url(r'^log_in$', views.logIn_test, name='log_in'),
    url(r'^user/(?P<user_id>\d+)$', views.show_user, name='show_user'),
]

belt_review_books/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='users')),
    url(r'^books/', include('apps.book_app.urls', namespace='books')),
]

apps/book_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from ..user_app.models import User

class AuthorManager(models.Manager):
    def create_author(self, name):
        return self.create(name=name)

class ReviewManager(models.Manager):
    def create_review(self, content, rating, book, user):
        return self.create(content=content, rating=rating, book=book, user=user)
    def avg_ratings(self, book):
        total_book_review = self.filter(book=book)
        user_count = total_book_review.count()
        total_ratings = 0
        for val in total_book_review:
            total_ratings += int(val.rating)
        if total_ratings < 4:
            stars = '* * * * * *'
        else:
            average_rating = total_ratings / user_count
            stars = average_rating * ' *'
        return stars
    def add_review(self, data, book, user):
        errors = {}
        if not len(data['review']):
            errors['review'] = 'Enter a reveiw'
        if not len(data['rating']):
            errors['rating'] = 'Select a rating'
        if len(errors):
            return errors
        else:
            return self.create(content=data['review'], rating=data['rating'], book=book, user=user)



class BookManager(models.Manager):
    def create_book(self, data, user):
        errors = {}
        if not len(data['title']):
            errors['title'] = 'Enter a book title'
        if not len(data['new_author']) and not len(data['existing_author']):
            errors['author'] = 'Enter or Select author'
        if not len(data['review']):
            errors['review'] = 'Enter a reveiw'
        if not len(data['rating']):
            errors['rating'] = 'Select a rating'
        if len(errors):
            return errors

        author_data = data['existing_author']
        if len(data['new_author']):
            author_data = data['new_author']
        if Author.objects.filter(name=author_data):
            author = Author.objects.get(name=author_data)
            if self.filter(title=data['title'], author=author):
                this_book = Book.objects.get(title=data['title'])
                review = Review.objects.create_review(data['review'], data['rating'],  this_book, user)
                return [this_book, author, review]
            else:
                book = self.create(title=data['title'], author=author)
                review = Review.objects.create_review(data['review'], data['rating'],  book, user)
                return [book, author, review]
        else:
            new_author = Author.objects.create_author(data['new_author'])
            book = self.create(title=data['title'],  author=new_author)
            review = Review.objects.create_review(data['review'], data['rating'],  book, user)
            return [book, new_author, review]



# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=100)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = AuthorManager()


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, related_name='books')
    average_rating = models.CharField(max_length=100)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = BookManager()

class Review(models.Model):
    content = models.TextField()
    rating = models.CharField(max_length=100)
    book = models.ForeignKey(Book, related_name='book_reviews')
    user = models.ForeignKey(User, related_name='user_reviews')
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = ReviewManager()

apps/book_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from ..user_app.models import User
from .models import Book, Author, Review
from django.core.urlresolvers import reverse
from django.contrib import messages

# Create your views here.
def average():
    for book in Book.objects.all():
        avg = Review.objects.avg_ratings(book)
        Book.objects.filter(id=book.id).update(average_rating=avg)

def home(request):
    average()
    if User.objects.filter(id=int(request.session['user_id'])):
        user = User.objects.get(id=int(request.session['user_id']))
        context = {'user': user, 'reveiws': Review.objects.all().order_by('-created_at')[:4], 'books': Book.objects.all().order_by('created_at')}
        return render(request, 'book_app/home.html', context)
    else:
        return redirect('users:index')

#TO SHOW 5 POSTS --- Entry.objects.all()[:5]

def add_book(request, id):
    user = User.objects.get(id=id)
    context = {'user': user, 'authors': Author.objects.all()}
    return render(request, 'book_app/add_book.html', context)


def create_data(request, id):
    user = User.objects.get(id=id)
    entry = Book.objects.create_book(request.POST, user)
    if type(entry) is dict:
        if 'title' in entry:
            messages.add_message(request, messages.INFO, entry['title'], extra_tags='title')
        if 'author' in entry:
            messages.add_message(request, messages.INFO, entry['author'], extra_tags='author')
        if 'review' in entry:
            messages.add_message(request, messages.INFO, entry['review'], extra_tags='review')
        if 'rating' in entry:
            messages.add_message(request, messages.INFO, entry['rating'], extra_tags='rating')
        return redirect(reverse('books:add_book', kwargs={'id': id }))
    else:
        return redirect(reverse('books:show_book', kwargs={'id': id, 'book_id': entry[0].id}))


def show_book(request, id, book_id):
    book = Book.objects.get(id=book_id)
    reviews = Review.objects.filter(book=book).order_by('-created_at')
    context = {'book': book, 'reviews': reviews, 'user_id': id,}
    return render(request, 'book_app/show_book.html', context)


def add_book_review(request, id, book_id):
    print '&&&&&&&&&&&&&&&&&&&&'
    user = User.objects.get(id=id)
    book = Book.objects.get(id=book_id)
    entry = Review.objects.add_review(request.POST, book, user)
    print entry, '***************'
    print '~~~~~~~~~~~~~~~'
    if type(entry) is dict:
        if 'review' in entry:
            messages.add_message(request, messages.INFO, entry['review'], extra_tags='review')
        if 'rating' in entry:
            messages.add_message(request, messages.INFO, entry['rating'], extra_tags='rating')
        return redirect(reverse('books:show_book', kwargs={'id': id, 'book_id': book.id}))
    else:
        print Review.objects.filter(book=book)
        return redirect(reverse('books:show_book', kwargs={'id': id, 'book_id': book.id}))

apps/book_app/templates/book_app/add_book.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>

  <body>
    <h2>Add a New Book Tittle and a Review</h2>
    <form action="{% url 'books:create_data' id=user.id %}" method="post">
      {% csrf_token %}
      Book Title: <input type="text" name="title"><p></p>
      {% if messages %}
        {% for message in messages %}
          {% if 'title' in message.tags %}
              <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}

      Author:<p></p>
      Choose from the list:
        <select name="existing_author">
          <option value=""></option>
        {% for author in authors %}
          <option >{{author.name}}</option>
        {% endfor %}
        </select><p></p>
        {% if messages %}
          {% for message in messages %}
            {% if 'author' in message.tags %}
                <p>{{message}}</p>
            {% endif %}
          {% endfor %}
        {% endif %}
      or add a new author: <input type="text" name="new_author"><p></p>

      Review: <textarea name="review" rows="8" cols="80"></textarea>
      {% if messages %}
        {% for message in messages %}
          {% if 'review' in message.tags %}
              <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}

    <label>Rating:
      <select name="rating">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
      </select> stars<p></p>
      {% if messages %}
        {% for message in messages %}
          {% if 'rating' in message.tags %}
              <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
      <input type="submit" value="Add Book and Review">
    </form>
  </body>

</html>

apps/book_app/templates/book_app/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      header h3, header a{
        display: inline-block;
        padding-right: 20px;
      }
      span{
        color: green;
      }
      div{
        marging-bottom: 10px;
        display: inline-block;
        width: 60%;
      }
      section{
        display: inline-block;
        width: 65%;
      }
      aside{
        display: inline-block;
        width: 25%;
        margin-left: 40px;
        height: 400px;
        vertical-align: top;
        overflow: scroll;
        background: grey;
      }
    </style>
  </head>
  <body>
    <header>
      <h3>Welcome, {{user.name}}! ~~~ {{user.id}} </h3>

      <a href="{% url 'books:add_book' id=user.id %}">Add Book and Review</a>
      <a href="{% url 'users:index' %}">Logout</a>
    </header>

    <section>
      <h2>Recent Book Reviews: </h2>
      {% for review in reveiws %}
        {% load humanize %}
        <div>
          <h3><a href="{% url 'books:show_book' id=user.id book_id=review.book.id %}">{{review.book.title}}</a></h3>
          <p>{{review.book.average_rating}}</p>
          <p><a href="{% url 'users:show_user' user_id=review.user.id %}">{{review.user.name}}</a> says {{review.content}}</p>
          <h5>{{review.created_at|naturaltime}}</h5>
        </div>
      {% endfor %}
    </section>

    <aside>
      {% for book in books %}
        <p><a href="{% url 'books:show_book' id=user.id book_id=book.id %}">{{book.title}}</a></p>
      {% endfor %}
    </aside>

  </body>
</html>