apps/book_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'books'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<id>\d+)/add_book$', views.add_book, name='add_book'),
    url(r'^(?P<id>\d+)/$', views.create_data, name='create_data'),
    url(r'^(?P<id>\d+)/(?P<book_id>\d+)/book_review$', views.show_book, name='show_book'),
    url(r'^(?P<id>\d+)/(?P<book_id>\d+)/add_review$', views.add_book_review, name='add_book_review'),
]

apps/user_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sign_up$', views.signUp_test, name='sign_up'),
    url(r'^log_in$', views.logIn_test, name='log_in'),
    url(r'^user/(?P<user_id>\d+)$', views.show_user, name='show_user'),
]

belt_review_books/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='users')),
    url(r'^books/', include('apps.book_app.urls', namespace='books')),
]

apps/user_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import bcrypt, re
EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
NAME_REGEX = re.compile(r'[a-zA-Z0-9.,-]*$')

class UserManager(models.Manager):
    def sign_up(self, data):
        errors = {}
        if ( not NAME_REGEX.match(data['name']) or  not len(data['name']) or not len(data['username']) or not NAME_REGEX.match(data['username']) ):
            errors['name'] = 'Enter a valid name'
        if not EMAIL_REGEX.match(data['email']):
            errors['email'] = 'Enter a valid email'
        if self.filter(username=data['username']):
            errors['name_exist'] = 'This username is taken'
        if self.filter(email=data['email']):
            errors['email_exist'] = 'This email already exists'
        if len(data['password']) < 8:
            errors['password'] = 'Your password must be 8 characters or more'
        if data['confirm_password'] != data['password']:
            errors['confirm_password'] = 'Your password doesnt match'
        if len(errors):
            return errors
        else:
            hash_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            return self.create(name=data['name'], email=data['email'], password=hash_password, username=data['username'])

    def log_in(self, data):
        errors = {}
        if self.filter(email=data['email']):
            user = self.get(email=data['email'])
            password = data['password']
            hash_password = bcrypt.hashpw(password.encode(), user.password.encode())
            if (hash_password == user.password):
                return user
            else:
                errors['password'] = 'Wrong password'
        else:
            errors['email'] = 'Invalid Email'
        return errors

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    username = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/user_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
from ..book_app.models import Book, Author, Review


# Create your views here.
def index(request):
    return render(request, 'user_app/index.html')

def signUp_test(request):
    entry = User.objects.sign_up(request.POST)
    if not type(entry) is dict:
        request.session['user_id'] = entry.id
        return redirect('books:home') #redirect to the root named index
    else:
        if 'name' in entry:
            messages.add_message(request, messages.INFO, entry['name'], extra_tags='sign_up')
        if 'name_exist' in entry:
            messages.add_message(request, messages.INFO, entry['name_exist'], extra_tags='sign_up')
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='sign_up')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='sign_up')
        if 'confirm_password' in entry:
            messages.add_message(request, messages.INFO, entry['confirm_password'], extra_tags='sign_up')
        if 'email_exist' in entry:
            messages.add_message(request, messages.INFO, entry['email_exist'], extra_tags='sign_up')
        return redirect('users:index')

def logIn_test(request):
    entry = User.objects.log_in(request.POST)
    print entry
    if type(entry) is dict:
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='log_in')
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='log_in')
        return redirect('users:index')
    else:
        request.session['user_id'] = entry.id
        return redirect('books:home')

def show_user(request, user_id):
    user = User.objects.get(id=user_id)
    context = {'user': user}
    return render(request, 'user_app/user.html', context)

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      div{
        display: inline-block;
        width: 40%;
        border: 2px black solid;
        vertical-align: top;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    {{user_id}}
    <div>
      <h1>Sign Up Here</h1>
      <form action="{% url 'users:sign_up' %}" method="post">
        {% csrf_token %}
              First Name: <input type="text" name="name"><p></p>
              Username: <input type="text" name="username"><p></p>
              Email: <input type="email" name="email"><p></p>
              Password: <input type="text" name="password"><p></p>
              Confirm PS: <input type="text" name="confirm_password"><p></p>
              <input type="submit" value="Sign Up">
        {% if messages %}
          {% for message in messages %}
            {% if 'sign_up' in message.tags %}
               <p>{{message}}</p>
            {% endif %}
          {% endfor %}
        {% endif %}
      </form>
    </div>

    <div>
      <h1>Log In Here</h1>
      <form action="{% url 'users:log_in' %}" method="post">
        {% csrf_token %}
        Email: <input type="text" name="email">
        Password: <input type="text" name="password">
        <input type="submit" value="Log In!">
        {% if messages %}
          {% for message in messages %}
            {% if 'log_in' in message.tags %}
                <p>{{message}}</p>
            {% endif %}
          {% endfor %}
        {% endif %}
      </form>
    </div>

  </body>
</html>

apps/user_app/templates/user_app/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{% url 'books:home' %}">Home</a>
     <a href="{% url 'users:index' %}">Logout</a>
    <h3>User: {{user.username}} </h3>
    <h3>Name: {{user.name}}</h3>
    <h3>Email: {{user.email}}</h3>
    <h3>Total Reviews: {{user.user_reviews.count}}</h3>
    <ol>
      <p>Posted reviews on the following books:</p>
      {% for book in user.user_reviews.all %}
        <li>{{book.book.title}}</li>
      {% endfor %}
    </ol>
  </body>
</html>